language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $aws_access_key_id
    secret_access_key: $aws_secret_access_key
    bucket: $aws_site_s3_bucket
    region: $aws_site_s3_bucket_region
    local_dir: build
    acl: public_read
    on:
      branch: master